version: '3.8'
services:
  web:
    build:
      context: .
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld123
    ports:
      - "5433:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      # - "test_volume:/var/lib/postgresql/data"

# volumes:
#   test_volume:
#     external: true